title: NZ Raid Theorycrafting
description: Tomb of Nazarick's Theory Crafters for Raid: Shadow Legends 
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
