title: "NZ | Raid Theorycraft"
description: "Tomb of Nazarick's Theory Craft for Raid: Shadow Legends"
theme: just-the-docs
color_scheme: dark

url: https://rsl-theorycraft.github.io/
logo: "/images/site-logo.png"

plugins:
  - jekyll-spaceship
