backend:
  name: git-gateway
  branch: main

media_folder: images/uploads

collections:
  - name: folders
    label: Folders
    label_singular: Folder
    filter: { field: "has_children", value: true }
    create: true
    fields:
      - {label: "Has children", name: "has_children", widget: "hidden", default: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "minimal"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: pages
    label: Pages
    label_singular: Page
    folder: pages
    filter: { field: "has_children", value: false }
    create: true
    fields:
      - {label: "Has children", name: "has_children", widget: "hidden", default: false}
      - {label: "Parent", name: "parent", widget: "relation", search_fields: ['title'], display_fields: ['title'], value_field: 'title', default: "Fire Knight", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

