backend:
  name: git-gateway
  branch: main

media_folder: images/uploads

collections:
  - name: folders
    label: Folders
    label_singular: Folder
    folder: pages
    filter: { field: "has_children", value: true }
    create: true
    fields:
      - {label: "Has children", name: "has_children", widget: "hidden", default: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "minimal"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Nav order", name: "nav_order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: pages
    label: Pages
    label_singular: Page
    folder: pages
    filter: { field: "has_children", value: false }
    create: true
    fields:
      - {label: "Has children", name: "has_children", widget: "hidden", default: false}
      - {label: "Parent", name: "parent", widget: "relation", collection: 'Folders', search_fields: ['title'], display_fields: ['title'], value_field: 'title', default: "Fire Knight", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Nav order", name: "nav_order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: files
    label: Files
    label_singular: Files
    files: 
      - label: 'Home'
        name: 'home'
        file: 'index.md'
        fields:
          - {label: 'Nav order', name: 'nav_order', widget: 'hidden', default: 0}
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string", default: "Home"}
          - {label: "Body", name: "body", widget: "markdown"}
